server.servlet.context-path=/udanchoo
# Here 'test' is the database name

spring.datasource.url=jdbc:mysql://localhost:3306/udanchoodb?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

#spring.datasource.url=jdbc:mysql://localhost:3306/udanchoodb?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
#spring.datasource.username=root
#spring.datasource.password=myuserid

spring.datasource.testWhileIdle = true
spring.datasource.timeBetweenEvictionRunsMillis = 3600000
spring.datasource.validationQuery = SELECT 1


spring.datasource.driver-class-name=com.mysql.jdbc.Driver
# when i specify following property value as validate then i get active tinyint to boolean convert error. 
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type=TRACE
#spring.jpa.show-sql=true


#spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#spring.security.user.name=admin
#spring.security.user.password=admin

#spring.profiles.active=production



security.basic.enable=false
spring.mvc.view.prefix:/WEB-INF/jsp/
spring.mvc.view.suffix:.jsp


spring.thymeleaf.prefix=classpath:/thymeleaf-template/
spring.thymeleaf.suffix=.html
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration



spring.messages.always-use-message-format=false
spring.messages.basename=validation
spring.messages.cache-seconds=-1
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true

spring.hibernate.enhancer.enableDirtyTracking=true

## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=10MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file.upload-dir=c:/uploads/deals
file.upload-clientsdir=c:/uploads/clients
file.upload-usersdir=c:/uploads/users

file.upload-partnerlogodir=c:/uploads/partners/logo
spring.mvc.static-path-pattern=/uploads/**  # URL pattern for accessing the files

ftl.template.image.path=C:/uploads/freemarker-ref-images
spring.freemarker.settings.template_update_delay=0
email.client.from=UdanChoo Sales <query@udanchoo.com>

#Following code will stop all email communication to client. 
email.client.valid=true

#following code will stop all internal email notifications. 
email.internal.valid=true

#following email id will be in bcc on all communication if enabled. 
all.email.notify.communication.active=false
email.notify.communication.email=sushil.chugh@gmail.com
email.preferred.default.email.cc=sales@udanchoo.com
##########
#spring.freemarker.template-loader-path=C:/UdanChoo/Intranet/UdanChooIntranet/src/main/webapp/resources/templates/
########################### EMAIL SETTINGS #############################################
#debug=true
 
#spring.mail.host=smtpout.secureserver.net
#spring.mail.port=465
#spring.mail.username=itdesk1@udanchoo.com
#spring.mail.password=MyCareer123$


#Please ensure that all other settings of B2b and normal email id belongs to same domain and same settings other than email id and password. else system wont accept. 
b2b.email.from=UdanChoo B2b Sales <b2bsales@udanchoo.com>
spring.b2b.mail.username=b2bsales@udanchoo.com
spring.b2b.mail.password=MyCareer123$
b2b.mail.port=587
b2b.mail.smtp.starttls.enable=false
b2b.mail.properties.mail.transport.protocol=smtp
b2b.mail.properties.mail.smtp.socketFactory.port = 25
b2b.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory


notification1.mail.username=admin@udanchoo.com
notification1.mail.password=MyCareer2505$

 
# TLS , port 587
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=false
 
# SSL, post 465
spring.mail.host=smtpout.secureserver.net
spring.mail.port=587
spring.mail.username=itdesk1@udanchoo.com
spring.mail.password=MyCareer123$
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.socketFactory.port = 25
#spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.imap.ssl.enable=true
spring.mail.properties.mail.imap.ssl.trust=*
# Other properties
spring.mail.properties.mail.debug=false
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

###########################################################################################
SMS_API_URL=http://smsinteract.in/SMSApi/send
SMS_API_USER=udanchoo
SMS_API_PASSWD=Ind@2022
SMS_SENDER_ID=UDANCH
COMPANY_NAME=UdanChoo.com

spring.jackson.serialization.fail-on-empty-beans=false

spring.profiles.active=dev
redirect.url=http://localhost:5173
