SRVC_CHECK_QTN_EXSTS_URL = http://127.0.0.1:8081/quotationservice/checkQuotationExists?quotationId={quotationId}&leadId={leadId}&version={version}
GENERATE_QTN_URL         = http://127.0.0.1:8081/quotationservice/generateQuotation?quotationId={quotationId}&manualConfigurationQuotationId={manualConfigurationQuotationId}
SRVC_DELETE_QTN_URL       = http://127.0.0.1:8081/quotationservice/deleteQuotation?quotationId={quotationId}&leadId={leadId}&version={version}
SRVC_SEND_EMAIL_QTN_URL    = http://127.0.0.1:8081/quotationservice/sendEmailQuotation
CHECK_ITINERARY_EXIST       = http://127.0.0.1:8081/quotationservice/getItineraryByQuotationId?quotationId={quotationId}

VIEW_QTN_URL=http://quotation.udanchhoo.com/quotationservice/viewQuotation?quotationId={quotationId}&leadId={leadId}&version={version}
DWNLOAD_QTN_URL=http://quotation.udanchhoo.com/quotationservice/downloadQuotation?quotationId={quotationId}&leadId={leadId}&version={version}d}