SRVC_CHECK_QTN_EXSTS_URL = http://localhost:8085/quotationservice/checkQuotationExists?quotationId={quotationId}&leadId={leadId}&version={version}

VIEW_QTN_URL=http://localhost:8085/quotationservice/viewQuotation?quotationId={quotationId}&leadId={leadId}&version={version}
DWNLOAD_QTN_URL=http://localhost:8085/quotationservice/downloadQuotation?quotationId={quotationId}&leadId={leadId}&version={version}

GENERATE_QTN_URL=http://localhost:8085/quotationservice/generateQuotation?quotationId={quotationId}&manualConfigurationQuotationId={manualConfigurationQuotationId}
SRVC_DELETE_QTN_URL = http://localhost:8085/quotationservice/deleteQuotation?quotationId={quotationId}&leadId={leadId}&version={version}
SRVC_SEND_EMAIL_QTN_URL = http://localhost:8085/quotationservice/sendEmailQuotation
QTN_BY_ID_SERVICE=http://localhost:8085/quotationservice/getFlightDetailsByQuotationId?quotationId={quotationId}

CHECK_ITINERARY_EXIST=http://localhost:8085/quotationservice/getItineraryByQuotationId?quotationId={quotationId}